### ISSUE TITLE
Management of TheCase/IPMIView.app repository

### ISSUE THREAD

**Issue by ChrisCarini** [TheCase/blog#1]
Hello @TheCase ,

First off, sorry for opening an issue on this repo - I am not able to open one on `TheCase/IPMIView.app` because it is archived.

I see that on 2021-04-01 (hopefully not as an April Fool's day joke 😄 ) you archived `TheCase/IPMIView.app` in the below two commits:

- https://github.com/TheCase/IPMIView.app/commit/36d5f65d434be737576e4a8445cb85888ba2d584
- https://github.com/TheCase/IPMIView.app/commit/e6ed79af8886134a9cb71dd1b76f64918d5b456c

I am interested in taking over ownership / management of this repository, as `IPMIView.app` is something I still use from time-to-time.

Upon taking over ownership, I would like to merge in the two changes from the below forks:

1. https://github.com/1ocate/IPMIView.app/commit/875d716710ae955f2144fc6e082258ad7d7cd3c1
    1. Updates the URL for finding the Linux download of `IPMIView` on SuperMicro's website (**Note:** The URL in this commit is for a user-facing SM webpage)
2. https://github.com/rmoriz/IPMIView.app/commit/37da1a28595231990a7363dbca501f2abc56d8df
    1. Updates the URL for finding the Linux download of `IPMIView` on SuperMicro's website (**Note:** The URL in this commit is for a user-facing SM webpage)
    2. Makes improvements upon the JRE that is used; this addressed an issue I saw which was similarly reported here https://github.com/TheCase/IPMIView.app/issues/13

Additionally, beyond that, I would like to eventually extend `script.sh` to try and automatically download the needed archive from SM's site to make the user experience that much easier/nicer for folks.

Let me know your thoughts!

Best,
Chris Carini

**Comment by TheCase** [comment]
I unarchived the repo and have sent you a collaborator access invite.
